### ISSUE TITLE
Option to show elapsed time instead of progression bar

### ISSUE THREAD

**Issue by champagj** [pimoroni/mopidy-pidi#15]
I have an application where I would require to show the actual elapsed time and/or total length of songs on the display.

Not sure if this would be possible via the pidi extension or via the or the st7789 driver but I think this is the right place. ?

Thanks!

**Comment by Gadgetoid** [comment]
The magic happens in `pidi-display-pil` which is here - https://github.com/pimoroni/pidi-plugins/tree/master/pidi-display-pil

The display plugins are only given two related values: `progress` and `elapsed`.

Where:
* elapsed = elapsed time in milliseconds
* progress = floating point progress from 0.0 to 1.0

Since  `progress = elapsed / length` then you can figure out the song length: `length = elapsed / progress`. IE: if the song is 2s long (2000ms) and 1s elapsed (1000ms) progress will be 0.5 and `1000ms / 0.5 = 2000ms`.

You'd then have to update the image rendering plugin that underpins all the display plugins:

https://github.com/pimoroni/pidi-plugins/blob/master/pidi-display-pil/pidi_display_pil/__init__.py

To display the elapsed/total time... somewhere!

**Comment by Gadgetoid** [comment]
An attempt to actually pull this off hasn't yielded very good results, due to the very lazy frame update rate this uses to avoid intensive system resource usage.

With the patch:

```diff
diff --git a/pidi-display-pil/pidi_display_pil/__init__.py b/pidi-display-pil/pidi_display_pil/__init__.py
index 24ae079..4bdce8f 100644
--- a/pidi-display-pil/pidi_display_pil/__init__.py
+++ b/pidi-display-pil/pidi_display_pil/__init__.py
@@ -193,6 +193,11 @@ class DisplayPIL(Display):
         rect = (5, 220, 235, 235)
         draw_progress_bar(self._overlay_draw, progress, max_progress, rect, colour)
 
+        if self._progress > 0:
+            total_time = self._elapsed / self._progress
+            songtime = "{}/{}".format(int(self._elapsed / 1000.0), int(total_time / 1000.0))
+            text_in_rect(self._overlay_draw, songtime, self._font_small, rect)
+
         # Volume bar
         volume = self._volume
         max_volume = 100
```

I can get a counter with a resolution of *seconds* that... uh... sometimes skips a second :grimacing:

**Comment by champagj** [comment]
Thanks for the tip!  I dont need precise timing by the second so it could work for my use case. I put the project on hold a while back but the prototype is still in one piece. Well 2 pieces to be honest..
