### ISSUE TITLE
Reducing CPU usage

### ISSUE THREAD

**Issue by kingosticks** [pimoroni/mopidy-pidi#2]
Mopidy isn't exactly super-fast when running on a Raspberry Pi Zero but it's even worse when the CPU is pegged at over 95% usage during playback with this extension enabled. I'm not convinced 30 redraws per second are required. And `threading.Event.wait()` has a pretty nasty implementation in Python 2. With [this quick hack](https://github.com/kingosticks/mopidy-pidi/commit/e422c67f426d9b0ac22099aa11ff16081d188eb7) the usage comes down to 55-70%. One annoying side-effect of this is that there's potentially a delay when stopping Mopidy, perhaps there is a better fix out there.

**Comment by Gadgetoid** [comment]
I wonder if it's worth attempting a dynamic framerate so that we can still have nice things like album art transitions, but then idle for regular display.

It's possible to do the maths and figure out for any given song how often the transport will visually update (since each horizontal pixel on the screen is going to equal some number or fraction of seconds, and we can only change by one pixel at a time) but I'd be given to being lazy and just sticking with 1FPS during "idle" times with immediate updates following things like button presses.

**Comment by kingosticks** [comment]
That sounds like a good idea.

**Comment by Gadgetoid** [comment]
Whew. That was exhaustive.

The crux of this issue, as you rightly observed, is that `event.wait` really wasn't doing what I understood it would do, resulting in - as far as I understand now - totally unbounded calls to the drawing handler. I think `event.wait` always returns immediately if the event `is_set()`, otherwise it waits for the given timeout value. A lack of understanding on my part.

This aside, I discussed this with the team for inspiration and found some good opportunities to optmise both `pidi-display-pil` and, as a consequence, `pidi-display-st7789` to avoid drawing calls unless:

1. The volume changes (and thus the bar needs to be redrawn)
2. The "progress" advances enough that it will visually change (determined in pixels)
3. An album art transition is happening
4. The song state has changed (play/pause)

See: https://github.com/pimoroni/pidi-plugins/pull/1

This requires the companion change in `mopidy-pidi` - https://github.com/pimoroni/mopidy-pidi/commit/9e7502c3729c991f01d9f338ab1d581526066483

From testing with top this appeared to have a dramatic impact on CPU usage.

**Comment by Gadgetoid** [comment]
Version `0.1.0` should fix half of this problem- hopefully moderately improving CPU usage by introducing an actual delay in the update loop. It also includes the new threaded album art download feature.

I'll release `v0.0.3` versions of `pidi-display-st7789` and `pidi-display-pil` soon- these are much more aggressive about how they update the back-buffer and display, to improve CPU usage even more.

In my tests on a Pi 4 it seems to be idling around 2% CPU, bursting around 30% on playback start (album art transitions invalidating the display cache) and then settling down to around 10-15% on playback.

**Comment by kingosticks** [comment]
I was going to ask about the album art download feature. Is it a conscious decision not to use the images provided by Mopidy? Sometimes your musicbrainz search doesn't find anything.

EDIT: Mopidy [Tracks](https://docs.mopidy.com/en/latest/api/models/#mopidy.models.Track) also have a `musicbrainz_id` field you could use.

**Comment by Gadgetoid** [comment]
It's mostly because "PiDi" came before the idea to directly integrate into Mopidy, and was designed to work connected to - in theory - any music player. The idea to integrate directly into Mopidy came later when we realised it would simplify everything and also perform much better.

There's no reason why `mopidy-pidi` couldn't use Mopidy album art, however, do you have a good example of how to accomplish this? I tried printing out `track.album.images` and get only an empty set.

The musicbrainz_id should come in super useful if it's available for sources like Spotify, much less of a fudge than doing a title-based search at least.

**Comment by kingosticks** [comment]
`Track.album.images` [is deprecated](https://docs.mopidy.com/en/latest/changelog/#models) in favour of https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.get_images

Note that if you are playing local files, and there wasn't any local album art found during the scan, you'll get an empty dictionary from `get_images()`; in that case your musicbrainz art grabber would still be useful. But the Spotify backend will always provide artwork.

**Comment by Gadgetoid** [comment]
Ah, brilliant- I had to put my Spotify Client ID and Secret in (I've been lazily using my setup without them) but once those were in place I now get:

```
{'spotify:track:2yLMuUJ8xXBOzdbRE5ZkJW': (Image(height=640, uri='https://i.scdn.co/image/ab67616d0000b2736d4fb043844cf504958a202b', width=640), Image(height=300, uri='https://i.scdn.co/image/ab67616d00001e026d4fb043844cf504958a202b', width=300), Image(height=64, uri='https://i.scdn.co/image/ab67616d000048516d4fb043844cf504958a202b', width=64))}
```

Which is definitely something I can work with in the plugin host- eliminating the need for MusicBrainz on all Spotify content. Thank you for pointing me in the right direction.

**Comment by kingosticks** [comment]
> eliminating the need for MusicBrainz on all Spotify content.

I think you could skip using MusicBrainz regardless of backend, unless `get_images` doesn't give you anything. 

Using `get_images` for Local music allows users to have whatever artwork they decide to put in their media directory. It also allows backends like TuneIn and Podcast to provide sensible artwork where MusicBrainz would simply fail.

**Comment by Gadgetoid** [comment]
After starting work on this feature last night and losing it to a snapped SD card (tossed my Pi in the bottom of my bag with no case on, like the maverick I am) I whipped it up again this morning for testing: https://github.com/pimoroni/mopidy-pidi/pull/4

There are, likely, a few bugs. Notably I should identify which image to use in a less crude way than: https://github.com/pimoroni/mopidy-pidi/pull/4/files#diff-e4eb73fad473ace8de867f0435a39a17R126

It's so much quicker than a MusicBrainz lookup, although I still have to grab the URLs and cache them locally so that the PIL-based display plugin can load them.

**Comment by Gadgetoid** [comment]
I think this thread has run its course. Thank you for your input!
